### ISSUE TITLE
Clarify source code license / 標明程式碼授權

### ISSUE THREAD

**Issue by rschiang** [g0v/moedict-data-terms#1]
這次萌典松提案要做國教院學術辭典的資料整理，剛剛好就挖出了這個古早的 repo、發現裡面已經有針對機關雙語翻譯部分作出初步整理了。然而當時上傳的程式碼並沒有特別註明以什麼方式釋出，因此可能要請 @youchenlee 確認一下了。

萌典本身是 CC0（最大限度內放棄著作權），這個專案學術詞彙（`academic-terms`）的部分我是採用 MIT License，提供參考。如果可以整個專案用同種授權的話那就再好不過啦。:)

**Comment by youchenlee** [comment]
感謝提醒。那麼一樣用 MIT License
thanks
